---
# Copyright 2018-2026 Fsas Technologies Inc.
# GNU General Public License v3.0+ (see [LICENSE.md](LICENSE.md) or https://www.gnu.org/licenses/gpl-3.0.txt)

# example playbook for module 'irmc_eventlog'
# to handle iRMC eventlogs

# variables not defined in this playbook are expected to be provided
# elsewhere, e.g. in group_vars/all

- name: Usage examples for irmc_eventlog
  connection: local
  hosts: iRMC_group

  # vars:
  #   # iRMC login credentials
  #   irmc_user: "<username>"
  #   irmc_password: "<password>"
  #   # Note: set validate_certificate to false for self-signed certificate
  #   validate_certificate: false

  gather_facts: false

  tasks:
    # List iRMC InternalEventLog
    - name: List and show iRMC InternalEventLog
      tags:
        - list_internaleventlog
      block:
        - name: List iRMC InternalEventLog
          fsas.primergy.irmc_eventlog:
            irmc_url: "{{ inventory_hostname }}"
            irmc_username: "{{ irmc_user }}"
            irmc_password: "{{ irmc_password }}"
            validate_certs: "{{ validate_certificate }}"
            command: "list"
            eventlog_type: "InternalEventLog"
          delegate_to: localhost
          register: list_internaleventlog
        - name: Show list InternalEventLog
          ansible.builtin.debug:
            var: list_internaleventlog

    # List iRMC SystemEventLog
    - name: List and show iRMC SystemEventLog
      tags:
        - list_systemeventlog
      block:
        - name: List iRMC SystemEventLog
          fsas.primergy.irmc_eventlog:
            irmc_url: "{{ inventory_hostname }}"
            irmc_username: "{{ irmc_user }}"
            irmc_password: "{{ irmc_password }}"
            validate_certs: "{{ validate_certificate }}"
            command: "list"
            eventlog_type: "SystemEventLog"
          delegate_to: localhost
          register: list_systemeventlog
        - name: Show list SystemEventLog
          ansible.builtin.debug:
            var: list_systemeventlog

    # Get specific InternalEventLog entry information
    # Add '-e "id=xx"' to the command line argument of Playbook.
    - name: Get and show a specific InternalEventLog entry
      tags:
        - get_internaleventlog
      block:
        - name: Get specific InternalEventLog entry information
          fsas.primergy.irmc_eventlog:
            irmc_url: "{{ inventory_hostname }}"
            irmc_username: "{{ irmc_user }}"
            irmc_password: "{{ irmc_password }}"
            validate_certs: "{{ validate_certificate }}"
            command: "get"
            eventlog_type: "InternalEventLog"
            id: "{{ id | int }}"
          delegate_to: localhost
          register: get_internaleventlog
        - name: Show specific InternalEventLog
          ansible.builtin.debug:
            var: get_internaleventlog.eventlog_entry

    # Get specific SystemEventLog entry information
    # Add '-e "id=xx"' to the command line argument of Playbook.
    - name: Get and show a specific SystemEventLog entry
      tags:
        - get_systemeventlog
      block:
        - name: Get specific SystemEventLog entry information
          fsas.primergy.irmc_eventlog:
            irmc_url: "{{ inventory_hostname }}"
            irmc_username: "{{ irmc_user }}"
            irmc_password: "{{ irmc_password }}"
            validate_certs: "{{ validate_certificate }}"
            command: "get"
            eventlog_type: "SystemEventLog"
            id: "{{ id | int }}"
          delegate_to: localhost
          register: get_systemeventlog
        - name: Show get specific SystemEventLog
          ansible.builtin.debug:
            var: get_systemeventlog.eventlog_entry

    # Clear iRMC InternalEventLog
    - name: Clear iRMC InternalEventLog
      fsas.primergy.irmc_eventlog:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "clear"
        eventlog_type: "InternalEventLog"
      delegate_to: localhost
      tags:
        - clear_internaleventlog

    # Clear iRMC SystemEventLog
    - name: Clear iRMC SystemEventLog
      fsas.primergy.irmc_eventlog:
        irmc_url: "{{ inventory_hostname }}"
        irmc_username: "{{ irmc_user }}"
        irmc_password: "{{ irmc_password }}"
        validate_certs: "{{ validate_certificate }}"
        command: "clear"
        eventlog_type: "SystemEventLog"
      delegate_to: localhost
      tags:
        - clear_systemeventlog
